const LOCKS = {
  createDW: 'create-dw-lock',
  customOperation: 'custom-operation-lock',
  closeDW: 'close-dw-lock',
} as const;

const TAB_TO_SW_MESSAGE_TYPES = [
  'HAS_WORKER_REQUEST',
  'WORKER_PORTS',
  'TAB_READY',
  'RESEND_PORT',
  'FIND_TAB_TO_TERMINATE_WORKER',
  'ELECTED_TAB_TERMINATED_WORKER',
  'PROPAGATE_MESSAGE',
] as const;

const TAB_TO_DW_MESSAGE_TYPES = ['SW_PORTS', 'CAN_TERMINATE'] as const;

const SW_TO_TAB_MESSAGE_TYPES = [
  'PORT_READY',
  'CREATE_WORKER',
  'RESEND_PORT',
  'OP_SUCCESS',
  'HAS_WORKER_RESPONSE',
  'OP_ERROR',
  'ELECTED_TAB_SHOULD_TERMINATE_WORKER',
  'WORKER_TERMINATED',
  'WORKER_CUSTOM_MESSAGE',
  'PROPAGATED_MESSAGE',
] as const;

const SW_TO_DW_MESSAGE_TYPES = ['PING', 'OP'] as const;

const DW_TO_SW_MESSAGE_TYPES = [
  'PONG',
  'SUCCESS',
  'FAILURE',
  'CUSTOM',
] as const;

const DW_TO_TAB_MESSAGE_TYPES = ['PROCEED_TERMINATION'] as const;

export {
  DW_TO_SW_MESSAGE_TYPES,
  DW_TO_TAB_MESSAGE_TYPES,
  LOCKS,
  SW_TO_DW_MESSAGE_TYPES,
  SW_TO_TAB_MESSAGE_TYPES,
  TAB_TO_DW_MESSAGE_TYPES,
  TAB_TO_SW_MESSAGE_TYPES,
};
